# Generated by Django 3.0.3 on 2020-04-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
