# Generated by Django 3.0.3 on 2020-04-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.IntegerField(),
        ),
    ]
